// <auto-generated />
using System;
using InternalApi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternalApi.DataAccess.Migrations
{
    [DbContext(typeof(CurrencyDbContext))]
    [Migration("20250419210843_Changes")]
    partial class Changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cur")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternalApi.DataAccess.Models.CurrencyRate", b =>
                {
                    b.Property<int>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("date_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Currency", "DateId")
                        .HasName("pk_currency_rates");

                    b.HasIndex("DateId")
                        .HasDatabaseName("ix_currency_rates_date_id");

                    b.ToTable("currency_rates", "cur");
                });

            modelBuilder.Entity("InternalApi.DataAccess.Models.ExchangeDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.HasKey("Id")
                        .HasName("pk_exchange_dates");

                    b.ToTable("exchange_dates", "cur");
                });

            modelBuilder.Entity("InternalApi.DataAccess.Models.CurrencyRate", b =>
                {
                    b.HasOne("InternalApi.DataAccess.Models.ExchangeDate", "ExchangeDate")
                        .WithMany("CurrencyRates")
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_currency_rates_exchange_dates_date_id");

                    b.Navigation("ExchangeDate");
                });

            modelBuilder.Entity("InternalApi.DataAccess.Models.ExchangeDate", b =>
                {
                    b.Navigation("CurrencyRates");
                });
#pragma warning restore 612, 618
        }
    }
}
